- name: Config app flask
  hosts: josh-host
  become: yes
  become_method: sudo
  remote_user: #mettre son propre user
  tasks:
    - name: Installation postgresql
      apt:
        name: 
          - postgresql
        state: latest

    #Je veux copier le dossier ou se trouve mon ansible et tous mes fichier
    - name: Copier dossier git
      synchronize:
      #path ou se trouve mon playbook
        src: "{{ playbook_dir }}"
      #path a la racine de ma VM
        dest: ./
    #Installation de la librairie pour linker le script python à psql
    - name : Installation de psycopg2, flask, jinja2
      apt:
        name: 
          - python-psycopg2
          - python-psycopg2
          - python3-flask
          - python3-jinja2
        state: latest

    - name: Create user psql
      become: yes
      become_user: postgres
      postgresql_user:
        name: "test"
        password: "pw"
        role_attr_flags: "CREATEDB,NOSUPERUSER"

    - name: Create database
      become: yes
      become_user: postgres
      postgresql_db:
          name: "dbtest"
          owner: "postgres"

    - name: Execute script database.py
      command: python3 ./simplon_devcloud_ansible_vm_flask_postgres/database.py

    - name: Execute script app.py
      command: python3 ./simplon_devcloud_ansible_vm_flask_postgres/app.py