- name: VM Adlane config app flask
  hosts: josh-host
  become: yes
  become_method: sudo
  remote_user: adlane-vm-user
  tasks:
    #- apt:
    #    name: 
    #      - postgresql
    #    state: latest

    #Je veux copier le dossier ou se trouve mon ansible et tous mes fichier
    - name: Copier dossier git
      synchronize:
      #path ou se trouve mon playbook
        src: "{{ playbook_dir }}"
      #path a la racine de ma VM
        dest: ./
    #Installation de la librairie pour linker le script python à psql
    #- name : Installation de psycopg2
    #  apt:
    #    name: python-psycopg2
    #    state: latest
    #Run du script
    #- name: Create user psql
    #  postgresql_user:
    #    name: josh
    #    password: 123
    - name: Create user psql
      become: yes
      become_user: postgres
      postgresql_user:
        name: "test"
        password: "pw"
        role_attr_flags: "CREATEDB,NOSUPERUSER"

    - name: Create database
      become: yes
      become_user: postgres
      postgresql_db:
          name: "dbtest"
          owner: "postgres"

    - name: Execute script database
      command: python3 /home/adlane-vm-user/Brief25_Ansible_pg_flask/database.py
        